# Generated by Django 3.2.10 on 2022-01-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_alter_entry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(editable=False, max_length=300),
        ),
    ]
