# Generated by Django 3.2.10 on 2022-01-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
